language: python
python:
  - "3.5"
install:
  - pip install coveralls
  - pip install pytest-cov
  - pip install .
# command to run tests
script:
  - coverage run --source=peval setup.py test
  - coverage report -m
after_success:
  coveralls
