language: python
branches:
  only:
    - master
    - develop
# Workaround to make py3.7 work; see https://github.com/travis-ci/travis-ci/issues/9069
sudo: required
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
install:
  - pip install coveralls
  - pip install pytest-cov
  - pip install .
# command to run tests
script:
  - coverage run --source=peval setup.py test
  - coverage report -m
after_success:
  coveralls
